AWSTemplateFormatVersion: "2010-09-09"
Description: ECR repo test WM Node Test
Resources:
  AWSTrainingTestRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "milap-node-test"
Outputs:
  AWSTrainingTestArn:
    Value: !GetAtt AWSTrainingTestRepo.Arn
    Export:
      Name: AWSTrainingTestArn